### PR TITLE
Hotfix for K-Monitor

### PR DESCRIPTION
**Pull request by kistasi**
It's just a bad hotfix for adatsprint.k-monitor.hu. It's gány. :)

(we consulted with @skylark1848 about this)

### CODE REVIEW

**Comment by bmispelon** [comment]
Can you also generate the `.mo` file by running `./manage.py compilemessages`?

**Comment by kistasi** [comment]
I used this online tool: http://po2mo.net/

**Comment by bmispelon** [comment]
Merged and deployed. Thanks.

**Comment by kistasi** [comment]
Thanks!

**Pull request merged**
