### PR TITLE
Python 3 is not the primary Python version by default

### PR DESCRIPTION
**Pull request by kistasi**

### CODE REVIEW

**Comment by bmispelon** [comment]
Hi,

It should work if you run the commands from a (Python3) virtualenv as is documented.
What about adding a line about activating the virtualenv instead?

**Comment by kistasi** [comment]
Hi Baptiste,

Oh, I'm sorry, I made a mistake, because I created a Python 2 virtual enviroment, and I installed the project for that.

So I don't forget: If I have a Python 3 project, I need a Python 3 virtual envrioment!

I'm sorry to bother you :(

**Comment by bmispelon** [comment]
No problem, let me know if you find other ways to improve the instructions or the code :)

**Comment by bmispelon** [comment]
@kistasi By the way, if you want to help out, I just added a few issues to https://github.com/bmispelon/adatozz/issues.
I'll be working on them on Monday but if you have some time, feel free to pick up any of them before that.
I'm happy to answer questions too.

**Pull request closed without merging**
